// src/db/schema/cms.schema.js
import {
  pgTable,
  uuid,
  serial,
  text,
  integer,
  boolean,
  timestamp,
  json,
} from 'drizzle-orm/pg-core';

export const bannersTable = pgTable('banners', {
  id: uuid('id').defaultRandom().primaryKey(),
  title: text('title').notNull(),
  subtitle: text('subtitle'),
  imageUrl: text('image_url').notNull(),
  imageLayer1: text('image_layer_1'),
  imageLayer2: text('image_layer_2'),
  poeticLine: text('poetic_line'),
  description: text('description'),
  link: text('link').default('/products'),
  buttonText: text('button_text').default('Shop Now'),
  type: text('type').default('hero'),
  layout: text('layout').default('split'),
  isActive: boolean('is_active').default(true),
  order: integer('order').default(0),
  createdAt: timestamp('created_at').defaultNow(),
  templateType: text('template_type').default('standard'),
  config: json('config').default({}),
});

export const aboutUsTable = pgTable('about_us', {
  id: uuid('id').defaultRandom().primaryKey(),
  heroTitle: text('hero_title').default('DEVID AURA'),
  heroSubtitle: text('hero_subtitle').default('Est. 2023'),
  heroImage: text('hero_image').notNull(),
  pillar1Title: text('pillar_1_title').default('Unrefined Nature.'),
  pillar1Desc: text('pillar_1_desc'),
  pillar1Image: text('pillar_1_image'),
  pillar2Title: text('pillar_2_title').default('Liquid Patience.'),
  pillar2Desc: text('pillar_2_desc'),
  pillar2Image: text('pillar_2_image'),
  pillar3Title: text('pillar_3_title').default('The Human Canvas.'),
  pillar3Desc: text('pillar_3_desc'),
  pillar3Image: text('pillar_3_image'),
  foundersTitle: text('founders_title').default('Architects of Memory.'),
  foundersQuote: text('founders_quote'),
  foundersDesc: text('founders_desc'),
  foundersImage: text('founders_image'),
  founder1Name: text('founder_1_name').default('Harsh'),
  founder1Role: text('founder_1_role').default('The Nose'),
  founder2Name: text('founder_2_name').default('Yomesh'),
  founder2Role: text('founder_2_role').default('The Eye'),
  footerTitle: text('footer_title').default('Define Your Presence.'),
  footerImageDesktop: text('footer_image_desktop'),
  footerImageMobile: text('footer_image_mobile'),
});

export const testimonials = pgTable('testimonials', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  title: text('title'),
  text: text('text').notNull(),
  rating: integer('rating').notNull(),
  avatar: text('avatar'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});
