CREATE TABLE "about_us" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"hero_title" text DEFAULT 'DEVID AURA',
	"hero_subtitle" text DEFAULT 'Est. 2023',
	"hero_image" text NOT NULL,
	"pillar_1_title" text DEFAULT 'Unrefined Nature.',
	"pillar_1_desc" text,
	"pillar_1_image" text,
	"pillar_2_title" text DEFAULT 'Liquid Patience.',
	"pillar_2_desc" text,
	"pillar_2_image" text,
	"pillar_3_title" text DEFAULT 'The Human Canvas.',
	"pillar_3_desc" text,
	"pillar_3_image" text,
	"founders_title" text DEFAULT 'Architects of Memory.',
	"founders_quote" text,
	"founders_desc" text,
	"founders_image" text,
	"founder_1_name" text DEFAULT 'Harsh',
	"founder_1_role" text DEFAULT 'The Nose',
	"founder_2_name" text DEFAULT 'Yomesh',
	"founder_2_role" text DEFAULT 'The Eye',
	"footer_title" text DEFAULT 'Define Your Presence.',
	"footer_image_desktop" text,
	"footer_image_mobile" text
);
